#! /usr/local/bin/python3.10

"""
    FAIRE UN SCRIPT QUI SUIS UN LIEN EST QUI SUIS LES LIEN QUI EST DANS LE LIEN
    TOUT CA C'EST RECURSIF, EN MVC
    LES LIENS SONT ENREGISTREZ DANS UN FICHIER EN JSON
    LES CLEF C'EST LE SITE QUI CONTIENT LE LIEN EST SONT LIEN 
"""
